# Generated by Django 4.0.1 on 2022-01-21 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=256)),
                ('estimed_time', models.DateTimeField(default=datetime.datetime(2022, 1, 28, 10, 43, 19, 607142))),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
